spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dummy
            client-secret: dummy
          naver:
            client-id: dummy
            client-secret: dummy
          google:
            client-id: dummy
            client-secret: dummy

  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: test-secret

openai:
  api-key: dummy-key
  model: gpt-3.5-turbo
  url: https://api.openai.com/v1/chat/completions
  embedding-model: text-embedding-3-large
  embedding-url: https://api.openai.com/v1/embeddings
